services:
  swarmui:
    image: swarmui
    user: ${HOST_UID:-1000}:${HOST_GID:-1000}
    cap_drop:
      - ALL
    build:
      context: .
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
      dockerfile: launchtools/StandardDockerfile.docker
    container_name: swarmui
    # uncomment `network_mode: host` if you want to access other services on the host network (eg a separated comfy instance)
    # network_mode: host
    volumes:
      - ${SWARMUI_DATA_PATH:-./Data}:/SwarmUI/Data
      - ${SWARMUI_BACKEND_PATH:-./dlbackend}:/SwarmUI/dlbackend
      - ${SWARMUI_DLNODES_PATH:-./DLNodes}:/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes
      - ${SWARMUI_MODELS_PATH:-./Models}:/SwarmUI/Models
      - ${SWARMUI_OUTPUT_PATH:-./Output}:/SwarmUI/Output
      - ${SWARMUI_WORKFLOWS_PATH:-./CustomWorkflows}:/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/CustomWorkflows
    ports:
      - "${SWARMUI_PORT:-7801}:7801"
    environment:
      - PUID=${HOST_UID:-1000}
      - PGID=${HOST_GID:-1000}
      - TZ=${TZ:-UTC}
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # change the count to the number of GPUs you want to use.
              count: 1
              capabilities: [gpu]
