name: Docker Build and Push

on:
  schedule:
    # Run once a day at midnight UTC
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:
  # Run on push to master branch
  push:
    branches:
      - master

jobs:
  sync-with-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/mcmonkeyprojects/SwarmUI.git
          git fetch upstream
          
      - name: Sync with upstream
        run: |
          git checkout master
          git merge upstream/master --no-edit
          git push origin master

  docker-build-push:
    needs: sync-with-upstream
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./launchtools/StandardDockerfile.docker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/swarmui:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/swarmui:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/swarmui:buildcache,mode=max 
